################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
ARCHIVES := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/Invn/Devices/Drivers/Ak0991x \
src/Invn/Devices/Drivers/Icm20948 \
src/bluetooth \
src/converters \
src/coredev \
src/display \
src/display/fonts/FreeMono \
src/display/fonts/FreeSans \
src/display/fonts/FreeSerif \
src/display/fonts \
src/imu \
src/micro-ecc \
src/miscdev \
src/nRF5_SDK/ble/ble_advertising \
src/nRF5_SDK/ble/ble_dtm \
src/nRF5_SDK/ble/ble_link_ctx_manager \
src/nRF5_SDK/ble/ble_racp \
src/nRF5_SDK/ble/ble_radio_notification \
src/nRF5_SDK/ble/ble_services/ble_bas \
src/nRF5_SDK/ble/ble_services/ble_dfu \
src/nRF5_SDK/ble/ble_services/ble_dis \
src/nRF5_SDK/ble/common \
src/nRF5_SDK/ble/nrf_ble_gatt \
src/nRF5_SDK/ble/nrf_ble_qwr \
src/nRF5_SDK/ble/nrf_ble_scan \
src/nRF5_SDK/ble/peer_manager \
src/nRF5_SDK/fprintf \
src/nRF5_SDK/libraries/atomic \
src/nRF5_SDK/libraries/atomic_fifo \
src/nRF5_SDK/libraries/atomic_flags \
src/nRF5_SDK/libraries/balloc \
src/nRF5_SDK/libraries/crypto/backend/cc310 \
src/nRF5_SDK/libraries/crypto/backend/cc310_bl \
src/nRF5_SDK/libraries/crypto/backend/nrf_hw \
src/nRF5_SDK/libraries/crypto \
src/nRF5_SDK/libraries/ecc \
src/nRF5_SDK/libraries/experimental_section_vars \
src/nRF5_SDK/libraries/fds \
src/nRF5_SDK/libraries/fstorage \
src/nRF5_SDK/libraries/log/src \
src/nRF5_SDK/libraries/mem_manager \
src/nRF5_SDK/libraries/memobj \
src/nRF5_SDK/libraries/queue \
src/nRF5_SDK/libraries/ringbuf \
src/nRF5_SDK/libraries/scheduler \
src/nRF5_SDK/libraries/sha256 \
src/nRF5_SDK/libraries/strerror \
src/nRF5_SDK/libraries/timer \
src/nRF5_SDK/libraries/usbd \
src/nRF5_SDK/libraries/usbd/class/audio \
src/nRF5_SDK/libraries/usbd/class/cdc/acm \
src/nRF5_SDK/libraries/usbd/class/dummy \
src/nRF5_SDK/libraries/usbd/class/hid \
src/nRF5_SDK/libraries/usbd/class/hid/generic \
src/nRF5_SDK/libraries/usbd/class/hid/kbd \
src/nRF5_SDK/libraries/usbd/class/hid/mouse \
src/nRF5_SDK/libraries/usbd/class/msc \
src/nRF5_SDK/libraries/usbd/class/nrf_dfu_trigger \
src/nRF5_SDK/libraries/util \
src/nRF5_SDK/nrfx/drivers/src \
src/nRF5_SDK/nrfx/hal \
src/nRF5_SDK/nrfx/legacy \
src/nRF5_SDK/nrfx/soc \
src/nRF5_SDK/proprietary_rf/esb \
src/nRF5_SDK/softdevice/common \
src/nrf5_SDK_Mesh/access/src \
src/nrf5_SDK_Mesh/bearer/src \
src/nrf5_SDK_Mesh/core/src \
src/nrf5_SDK_Mesh/dfu/src \
src/nrf5_SDK_Mesh/friend/src \
src/nrf5_SDK_Mesh/gatt/src \
src/nrf5_SDK_Mesh/models/foundation/config/src \
src/nrf5_SDK_Mesh/models/foundation/health/src \
src/nrf5_SDK_Mesh/models/model_spec/common/src \
src/nrf5_SDK_Mesh/models/model_spec/generic_dtt/src \
src/nrf5_SDK_Mesh/models/model_spec/generic_level/src \
src/nrf5_SDK_Mesh/models/model_spec/generic_onoff/src \
src/nrf5_SDK_Mesh/models/model_spec/generic_ponoff/src \
src/nrf5_SDK_Mesh/prov/src \
src/nrf5_SDK_Mesh/stack/src \
src/sensors \

